sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: xxxx
    access-key-id: xxxx
    access-key-secret: xxxx
    bucket-name: ##sky-take-out
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: xxxx
    secret: xxxx
  shop:
    address: xx
  baidu:
    ak: xx
  file:
    dataTemplate: "运营数据报表模板.xlsx"